#__________________________________________#
#course: CS216 - 002 
#Program Assignment 3 
#Date : 04 / 14 / 15
#Purpose: makefile 
#Author: Ajin Sunny
#__________________________________________#

#creates the object 

all: CS216PA3

CS216PA3: main.o 
		g++ -o CS216PA3 main.o

main.o: main.cpp stack.h
		g++ -c -std=c++11 main.cpp

clean:
		rm *.o




















